name: stefanie-kaindl-cranio
static_sites:
  - name: web
    github:
      repo: ChristianLutzCL/stefanie-kaindl-cranio
      branch: main
      deploy_on_push: true
    build_command: npm run build
    output_dir: out
    routes:
      - path: /
    catchall_document: index.html
    error_document: 404.html
